version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    versioning-strategy: 'increase'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
  - package-ecosystem: github-actions
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
